// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityReportWeb.Database.Models;

#nullable disable

namespace SecurityReportWeb.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20251203055131_AddAlertStatusHistory")]
    partial class AddAlertStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityReportWeb.Database.Models.AlertStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HistoryId")
                        .HasName("PK_AlertStatusHistory_HistoryId");

                    b.HasIndex(new[] { "AlertId" }, "IX_AlertStatusHistory_AlertId");

                    b.HasIndex(new[] { "NewStatus" }, "IX_AlertStatusHistory_NewStatus");

                    b.HasIndex(new[] { "UpdatedAt" }, "IX_AlertStatusHistory_UpdatedAt");

                    b.ToTable("AlertStatusHistory", (string)null);
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuditId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.RiskDescription", b =>
                {
                    b.Property<Guid>("RiskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Cweid")
                        .HasColumnType("int")
                        .HasColumnName("CWEId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PluginId")
                        .HasColumnType("int")
                        .HasColumnName("PluginID");

                    b.Property<string>("Reference")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wascid")
                        .HasColumnType("int")
                        .HasColumnName("WASCId");

                    b.HasKey("RiskId")
                        .HasName("PK__RiskDesc__435363F6A0A1D0DB");

                    b.HasIndex(new[] { "Name" }, "RiskDescription_index_8");

                    b.HasIndex(new[] { "Name", "Signature" }, "UQ_RiskDescription_Name_Signature")
                        .IsUnique();

                    b.ToTable("RiskDescription", (string)null);
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.UrlList", b =>
                {
                    b.Property<Guid>("UrlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IP");

                    b.Property<string>("Manager")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ManagerMail")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OutsourcedVendor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskReportLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("UploadDate")
                        .HasColumnType("date");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("WebName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UrlId")
                        .HasName("PK__UrlLists__BDE12DF0431CD460");

                    b.HasIndex(new[] { "WebName" }, "UQ__UrlLists__987EC824CB54D070")
                        .IsUnique();

                    b.HasIndex(new[] { "Manager" }, "UrlLists_index_0");

                    b.ToTable("UrlLists");
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.ZapalertDetail", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("Attack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("ReportDay")
                        .HasColumnType("date");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("RootUrlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("AlertId")
                        .HasName("PK__ZAPAlert__EBB16AEDB761AB67");

                    b.HasIndex(new[] { "RootUrlId", "ReportDay" }, "ZAPAlertDetail_index_3");

                    b.HasIndex(new[] { "RootUrlId", "RiskName", "ReportDay" }, "ZAPAlertDetail_index_4");

                    b.HasIndex(new[] { "Url", "ReportDay" }, "ZAPAlertDetail_index_5");

                    b.HasIndex(new[] { "RiskName" }, "ZAPAlertDetail_index_6");

                    b.ToTable("ZAPAlertDetail", (string)null);
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.Zapreport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("GeneratedDay")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SiteUrlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zapsupporter")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ZAPSupporter");

                    b.Property<string>("Zapversion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ZAPVersion");

                    b.HasKey("ReportId")
                        .HasName("PK__ZAPRepor__D5BD48056EA5F36E");

                    b.HasIndex(new[] { "SiteUrlId", "GeneratedDay" }, "UQ_ZAPReport_SiteUrlId_GeneratedDay")
                        .IsUnique();

                    b.HasIndex(new[] { "GeneratedDate" }, "ZAPReport_index_2");

                    b.ToTable("ZAPReport", (string)null);
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.AlertStatusHistory", b =>
                {
                    b.HasOne("SecurityReportWeb.Database.Models.ZapalertDetail", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AlertStatusHistory_ZAPAlertDetail");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.ZapalertDetail", b =>
                {
                    b.HasOne("SecurityReportWeb.Database.Models.UrlList", "RootUrl")
                        .WithMany("ZapalertDetails")
                        .HasForeignKey("RootUrlId")
                        .IsRequired()
                        .HasConstraintName("FK_ZAPAlertDetail_UrlLists");

                    b.HasOne("SecurityReportWeb.Database.Models.Zapreport", "Report")
                        .WithMany("ZapalertDetails")
                        .HasForeignKey("RootUrlId", "ReportDay")
                        .HasPrincipalKey("SiteUrlId", "GeneratedDay")
                        .IsRequired()
                        .HasConstraintName("FK_ZAPAlertDetail_ZAPReport");

                    b.Navigation("Report");

                    b.Navigation("RootUrl");
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.Zapreport", b =>
                {
                    b.HasOne("SecurityReportWeb.Database.Models.UrlList", "SiteUrl")
                        .WithMany("Zapreports")
                        .HasForeignKey("SiteUrlId")
                        .IsRequired()
                        .HasConstraintName("FK_ZAPReport_UrlLists");

                    b.Navigation("SiteUrl");
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.UrlList", b =>
                {
                    b.Navigation("ZapalertDetails");

                    b.Navigation("Zapreports");
                });

            modelBuilder.Entity("SecurityReportWeb.Database.Models.Zapreport", b =>
                {
                    b.Navigation("ZapalertDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
